- hosts: localhost
  become: true
  pre_tasks:
      - name: Update cache
        apt:
            update_cache: true
  tasks:
      - name: Install essentials
        apt:
            name:
                - 'git'
                - 'zsh'
                - 'curl'
                - 'stow'
                - 'nodejs'
                - 'npm'
                - 'neovim'
        tags:
            - essentials
      - name: Get dotfiles repository
        git:
            repo: 'https://github.com/bazyli/.dotfiles.git'
            dest: '~/.dotfiles'
        tags:
            - dotfiles
      - name: Change shell
        shell: chsh -s `which zsh`
        tags:
            - zsh
      - name: Install ohmyzsh
        shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        tags:
            - zsh
      - name: Install zsh autosuggestions
        git:
            repo: 'https://github.com/zsh-users/zsh-autosuggestions'
            dest: '~/.oh-my-zsh/custom/plugins/zsh-autosuggestions'
        tags:
            - zsh
      - name: Stow all dotfiles
        shell: rm ~/.zshrc && cd ~/.dotfiles/ && stow dotfiles
        tags:
            - dotfiles
      - name: Install n
        npm:
            name: n
            global: true
        tags:
            - node
      - name: Select node version 14
        shell: n 14
        tags:
            - node
      - name: Install typescript
        npm:
            name: typescript
            global: true
        tags:
            - node
      - name: Install typescript language server
        npm:
            name: typescript-language-server
            global: true
        tags:
            - node
      - name: Install prettier
        npm:
            name: prettier
            global: true
        tags:
            - node
      - name: Install eslint
        npm:
            name: eslint
            global: true
        tags:
            - node
      - name: Install solidity language server
        npm:
            name: solidity-language-server
            global: true
        tags:
            - node
      - name: Install solidity prettifier
        npm:
            name: prettier-plugin-solidity
            global: true
        tags:
            - node
      - name: Install rust
        shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        tags:
            - rust
      - name: Install rust language server
        shell: PATH=$PATH:~/.cargo/bin rustup update && PATH=$PATH:~/.cargo/bin rustup component add rls rust-analysis rust-src
        tags:
            - rust
